# Generated by Django 5.2.15 on 2026-06-25 00:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
