# Generated by Django 5.2.15 on 2026-07-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Ημερομηνία γέννησης'),
        ),
        migrations.AddField(
            model_name='registration',
            name='fide_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='FIDE ID'),
        ),
    ]
