# Generated by Django 5.2.15 on 2026-09-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_registration_birth_date_registration_fide_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='verification_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
